# base
requires 'Mojo::Base';
requires 'Mojolicious';
requires 'DateTime::TimeZone';
requires 'Try::Tiny';

# libs
requires 'Array::Utils';
requires 'Capture::Tiny';
requires 'Const::Fast';
requires 'Cpanel::JSON::XS';
requires 'DateTime';
requires 'Dir::Self';
requires 'DBD::Pg';
requires 'DBI';
requires 'File::Temp';
requires 'SQL::Abstract::More';
requires 'Text::Levenshtein::XS';
requires 'YAML::XS';

# tests
requires 'Clone';
requires 'Devel::Cover::Report::Codecov';
requires 'Overload::FileCheck';
requires 'Test::Compile';
requires 'Test::Exception';
requires 'Test::MockModule';
requires 'Test::MockObject::Extends';
requires 'Test::MockSleep';
requires 'Test::MockTime';
requires 'Test::Output';
requires 'Test::Perl::Critic';
requires 'Test::Pod';
requires 'Test::Pod::Coverage';
