name: Mandyville Data Tests

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  perl-job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - '5.26'
    container:
      image: perldocker/perl-tester:${{matrix.perl-version}}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: 'mandyville'
          POSTGRES_PASSWORD: ${{secrets.MANDYVILLE_DB_PASS}}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    name: Perl Tests
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        env:
          MANDYVILLE_DB_HOST: postgres
          MANDYVILLE_DB_PASS: ${{secrets.MANDYVILLE_DB_PASS}}
        run: |
          apt install libdbd-pg-perl
          cpanm --installdeps --notest .
          prove -lr t
      - name: Run tests with coverage
        env:
          MANDYVILLE_DB_HOST: postgres
          MANDYVILLE_DB_PASS: ${{secrets.MANDYVILLE_DB_PASS}}
          COVERALLS_REPO_TOKEN: ${{secrets.COVERALLS_TOKEN}}
        run: |
          apt install libdbd-pg-perl
          cpanm --installdeps --notest .
          cover -test -silent -report Coveralls -make 'prove -lr t; exit $?;'
          
