name: Mandyville Data Tests

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  perl-job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - '5.32'
    container:
      image: perldocker/perl-tester:${{matrix.perl-version}}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: 'mandyville'
          POSTGRES_PASSWORD: ${{secrets.MANDYVILLE_DB_PASS}}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    name: Perl Tests
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Run tests
        id: run-tests
        env:
          MANDYVILLE_DB_HOST: postgres
          MANDYVILLE_DB_PASS: ${{secrets.MANDYVILLE_DB_PASS}}
        run: |
          apt clean
          wget http://deb.debian.org/debian/pool/main/libd/libdbi-perl/libdbi-perl_1.642-1+deb10u2_amd64.deb
          dpkg -i libdbi-perl_1.642-1+deb10u2_amd64.deb
          apt install -f
          apt install -y libdbd-pg-perl
          curl -s https://packagecloud.io/install/repositories/golang-migrate/migrate/script.deb.sh | bash
          apt install -y migrate=4.14.1 postgresql-client
          cpanm --installdeps --notest .
          prove -lr t
      - name: Run tests with coverage
        id: run-tests-with-coverage
        env:
          MANDYVILLE_DB_HOST: postgres
          MANDYVILLE_DB_PASS: ${{secrets.MANDYVILLE_DB_PASS}}
          COVERALLS_REPO_TOKEN: ${{secrets.COVERALLS_TOKEN}}
        run: |
          cover -test -silent -report Coveralls -make 'prove -lr t; exit $?;'
      - uses: act10ns/slack@v1
        env:
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()

